### ISSUE TITLE
Numpy error

### ISSUE THREAD

**Issue by robsonmarcelino** [lucas-campagna/mt5linux#15]
I tryed to install mt5linux with recent metatrader5 version and get this error.

importerror: numpy.core.multiarray failed to import

**Comment by darkpowerxo** [comment]
Hi, 
the **Numpy version requirement** is a **big issue** because I can't properly use it neither with tensoflow nor nnxruntime

`tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.21.4 which is incompatible.
tensorflow 2.12.0 requires protobuf!=4.21.0,!=4.21.1,!=4.21.2,!=4.21.3,!=4.21.4,!=4.21.5,<5.0.0dev,>=3.20.3, but you have protobuf 3.20.1 which is incompatible.
onnxruntime 1.14.1 requires numpy>=1.21.6, but you have numpy 1.21.4 which is incompatible.
onnxruntime-gpu 1.14.1 requires numpy>=1.21.6, but you have numpy 1.21.4 which is incompatible.`

hopefully someone can fix this asap

**Comment by darkpowerxo** [comment]
Could you please update the numpy dependencies:

`tensorflow 2.12.0 requires numpy<1.24,>=1.22, but you have numpy 1.24.2 which is incompatible.
mt5linux 0.1.9 requires numpy==1.21.4, but you have numpy 1.24.2 which is incompatible.`

**Comment by robsonmarcelino** [comment]
Resolved: pip install MetaTrader5==5.0.36
